pin boto3-stubs to 1.24.29 (#2578)
fix boto3-stubs 1.24.30 causing causing mypy tests to fail with the following

reconcile/utils/aws_api.py:11: error: Module "boto3" has no attribute "Session"; maybe "session"?  [attr-defined]