Adding our own implementation of raise_for_status
The response with status code >= 400 contains messages that
are not exposed by the requests builtin raise_for_status().

This patch adds our own raise_for_status version, which shows the
messages coming from the server.

Examples:

    >>> i = Image('registry.access.redhat.com/rhel8/redis-5')
    >>> i.get_tags()
    ...
    HTTPError: (403) Forbidden, This repo requires terms acceptance and is only available
    on registry.redhat.io

    >>> i = Image('registry.redhat.io/rhel8/redis-5')
    >>> i.get_tags()
    ...
    HTTPError: unable to retrieve auth token from https://registry.redhat.io/auth/realms/rhcc
    /protocol/redhat-docker-v2/auth?service=docker-registry&: (401) Unauthorized, Please login
    to the Red Hat Registry using your Customer Portal credentials. Further instructions can be
    found here: https://access.redhat.com/RegistryAuthentication

Signed-off-by: Amador Pahim <apahim@redhat.com>