pin boto3-stubs to 1.24.29
1.24.30 introduces an issue with the Session attribute

reconcile/utils/aws_api.py:11: error: Module "boto3" has no attribute "Session"; maybe "session"?  [attr-defined]